name: vms_visitor_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.6
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  get: 4.6.1
  pin_code_fields: ^7.3.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
